//! Rust-authored dashboard wire contracts.
//!
//! The dashboard API is versioned independently from the inference APIs.  The
//! DTOs remain serde's wire authority; Schemars reads those same types for the
//! checked-in TypeScript declarations and CSP-safe validators generated by
//! `dashboard-contracts`.  Nothing in this module runs on the request path.

use schemars::JsonSchema;
use serde::Serialize;
use std::collections::BTreeMap;

/// Current dashboard bootstrap, REST, and WebSocket schema version.
pub const DASHBOARD_SCHEMA_VERSION: u32 = 6;

/// Header carried by every `/dashboard/api/*` response.
pub const DASHBOARD_SCHEMA_HEADER: &str = "x-llmconduit-dashboard-schema";

/// CSP-safe bootstrap injected into the authenticated dashboard shell.
#[derive(Debug, Clone, Serialize, JsonSchema)]
pub struct DashboardBootstrap {
    pub authenticated: bool,
    pub csrf_token: String,
    pub mutations_enabled: bool,
    pub schema_version: u32,
}

/// Successful `POST /dashboard/api/flows/:id/kill` response.
#[derive(Debug, Clone, Serialize, JsonSchema)]
pub struct KillResponse {
    pub api_call_id: String,
    pub killed: bool,
}

/// One schema document containing every named dashboard contract.  This root is
/// used only to generate TypeScript declarations; endpoint validators are
/// generated from the individual roots returned by [`root_schemas`].
#[derive(JsonSchema)]
pub struct DashboardContracts {
    pub bootstrap: DashboardBootstrap,
    pub ws_snapshot: crate::dashboard_ws::SnapshotMessage,
    pub ws_frame: crate::dashboard_ws::DashboardFrame,
    pub flows_response: crate::dashboard_api::FlowsResponse,
    pub flow_summary: crate::dashboard_history::DurableFlowRollup,
    pub flow_detail: crate::dashboard_api::FlowDetailBody,
    pub metrics_response: crate::dashboard_ws::MetricsSnapshot,
    pub overview_response: crate::dashboard_api::OverviewResponse,
    pub topology_response: crate::dashboard_ws::TopologySnapshot,
    pub catalog_response: Vec<crate::dashboard_api::CatalogEntry>,
    pub snapshot_response: crate::dashboard_api::SnapshotResponse,
    pub history_response: crate::dashboard_api::HistoryResponse,
    pub theater_response: crate::dashboard_api::TheaterResponse,
    pub durability_status: crate::dashboard_api::DurabilityStatusResponse,
    pub kill_response: KillResponse,
    pub login_request: crate::dashboard_auth::LoginRequest,
}

/// Generate deterministic endpoint-root JSON Schemas.  A `BTreeMap` keeps file
/// output stable across runs so `contracts:check` is a byte-for-byte drift gate.
pub fn root_schemas() -> BTreeMap<&'static str, schemars::Schema> {
    BTreeMap::from([
        ("bootstrap", wire_schema_for::<DashboardBootstrap>()),
        (
            "catalog",
            wire_schema_for::<Vec<crate::dashboard_api::CatalogEntry>>(),
        ),
        (
            "flow-detail",
            wire_schema_for::<crate::dashboard_api::FlowDetailBody>(),
        ),
        (
            "flows",
            wire_schema_for::<crate::dashboard_api::FlowsResponse>(),
        ),
        (
            "flow-summary",
            wire_schema_for::<crate::dashboard_history::DurableFlowRollup>(),
        ),
        ("kill", wire_schema_for::<KillResponse>()),
        (
            "history",
            wire_schema_for::<crate::dashboard_api::HistoryResponse>(),
        ),
        (
            "durability",
            wire_schema_for::<crate::dashboard_api::DurabilityStatusResponse>(),
        ),
        (
            "metrics",
            wire_schema_for::<crate::dashboard_ws::MetricsSnapshot>(),
        ),
        (
            "overview",
            wire_schema_for::<crate::dashboard_api::OverviewResponse>(),
        ),
        (
            "snapshot",
            wire_schema_for::<crate::dashboard_api::SnapshotResponse>(),
        ),
        (
            "topology",
            wire_schema_for::<crate::dashboard_ws::TopologySnapshot>(),
        ),
        (
            "theater",
            wire_schema_for::<crate::dashboard_api::TheaterResponse>(),
        ),
        (
            "ws-frame",
            wire_schema_for::<crate::dashboard_ws::DashboardFrame>(),
        ),
        (
            "ws-snapshot",
            wire_schema_for::<crate::dashboard_ws::SnapshotMessage>(),
        ),
    ])
}

/// Schema used to generate the shared named TypeScript declarations.
pub fn declarations_schema() -> schemars::Schema {
    wire_schema_for::<DashboardContracts>()
}

fn wire_schema_for<T: JsonSchema>() -> schemars::Schema {
    schemars::generate::SchemaSettings::draft2020_12()
        .for_serialize()
        .into_generator()
        .into_root_schema_for::<T>()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generated_schema_pins_version_and_every_failover_variant() {
        let bootstrap = serde_json::to_value(wire_schema_for::<DashboardBootstrap>()).unwrap();
        assert_eq!(bootstrap["properties"]["schema_version"]["type"], "integer");

        let declarations = serde_json::to_string(&declarations_schema()).unwrap();
        for variant in [
            "provider_failed",
            "request_rejected",
            "terminal_no_failover",
        ] {
            assert!(
                declarations.contains(variant),
                "generated schema omitted {variant}"
            );
        }
    }

    #[test]
    fn every_runtime_validated_root_is_generated() {
        let roots = root_schemas();
        assert_eq!(
            roots.keys().copied().collect::<Vec<_>>(),
            vec![
                "bootstrap",
                "catalog",
                "durability",
                "flow-detail",
                "flow-summary",
                "flows",
                "history",
                "kill",
                "metrics",
                "overview",
                "snapshot",
                "theater",
                "topology",
                "ws-frame",
                "ws-snapshot",
            ]
        );
    }
}
